# Utilise la dernière version d'Ubuntu comme base
FROM ubuntu:latest

# Met à jour la liste des paquets
RUN apt-get update && \
    apt-get upgrade -y

# Définit la commande exécutée par défaut
CMD echo "Hello, World!"
